<a href="https://colab.research.google.com/github/therealmolf/Matrix-Form-of-Simplex-Iteration-in-Pytorch/blob/master/Matrix_Form_of_Simplex_Iteration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# C refers to coefficients of Decision Variables in the Objective Function
# C_b refers to coefficients of Basic Variables in the Objective Function
# B refers to the coefficients of Basic Variables in Tech Constraints
# b refers to the RHS of Constraints
# A refers to the coefficients of Decision Variables in the Tech Constraints

In [ ]:
import ipywidgets as widgets
import torch
import tensorflow.compat.v2 as tf
import inspect

In [ ]:
inspect.getfullargspec(widgets.Text)

FullArgSpec(args=['cls'], varargs='args', varkw='kwargs', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})

In [ ]:
?widgets.*

In [ ]:
text = 'Some text'

htmlWidget = widgets.HTML(value = f"<b><font color='red'>{text}</b>")
display(htmlWidget)

HTML(value="<b><font color='red'>Some text</b>")

In [ ]:

x_1 = widgets.Text(value='x_1')
x_2 = widgets.Text(value='x_2')
x_3 = widgets.Text(value='x_3')
x = widgets.HBox([x_1, x_2, x_3])
print("Coefficients of max z = ()x_1 + ()x_2 + ()x_3")
display(x)

Coefficients of max z = ()x_1 + ()x_2 + ()x_3


In [ ]:
# constraints input
c_1 = widgets.Text(value='x_1')
c_2 = widgets.Text(value='x_2')
c_3 = widgets.Text(value='x_3')
rhs_1 = widgets.Text(value='rhs')
c_row1 = widgets.HBox([c_1, c_2, c_3, rhs_1])

c_4 = widgets.Text(value='x_1')
c_5 = widgets.Text(value='x_2')
c_6 = widgets.Text(value='x_3')
rhs_2 = widgets.Text(value='rhs')
c_row2 = widgets.HBox([c_4, c_5, c_6, rhs_2])

c_7 = widgets.Text(value='x_1')
c_8 = widgets.Text(value='x_2')
c_9 = widgets.Text(value='x_3')
rhs_3 = widgets.Text(value='rhs')
c_row3 = widgets.HBox([c_7, c_8, c_9, rhs_3])

constraint_table = widgets.VBox([c_row1, c_row2, c_row3])
print('Coefficients of Constraints')
display(constraint_table)

Coefficients of Constraints


In [ ]:
# layout and styling of widgets to make textboxes smaller and more readable with labels
# figure out how we the app can work with less coefficients
# do the tensor calculations with pytorch

**Define own inverse function using Tensorflow**


*   A*A_inv = I




In [ ]:
def inverse_func(tensor_input):
  return tf.linalg.inv(tensor_input)



def new_objective_row(Cb,B_inv, A, C):
  '''
  returns the new objective row as a tensor
  '''
  new_constraints = B_inv@A
  updated_obj = Cb@new_constraints
  
  return updated_obj - C

def new_B_inv():
  '''
    from new_objective row, determine if optimal or not
    get basic variable column vectors
    then get new B matrix
    get inv of new B matrix
  '''
  pass

def get_solution():
  '''
    get optimal solution iteratively given initial B, A, C
  '''
  pass

# Stuff that change
sample_B = tf.constant([[2.,0., 1.],
                      [1.,0.,1.],
                      [1.,-1.,2. ]])

sample_Cb = tf.constant([5.,0.,4.])


# Stuff that dont change
sample_A = tf.constant([2.,1.,1.,0.,0.,0.],
                        [1.,1.,0.,1.,0.,0.],
                        [1.,2.,0.,0.,-1.,1.]])
sample_b = tf.constant([[20.,18.,12.]])

sample_C = tf.constant([5.,4.,0.,0.,0.])

B_inv = inverse_func(sample_b)

print(B_inv)

tf.Tensor(
[[ 1. -1.  0.]
 [-1.  3. -1.]
 [-1.  2.  0.]], shape=(3, 3), dtype=float32)


In [ ]:
??tf.linalg.inv